"""remove email

Revision ID: 81068c538660
Revises: ca1014f0f3df
Create Date: 2026-08-29 16:06:08.215814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81068c538660'
down_revision = 'ca1014f0f3df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=1)

    # ### end Alembic commands ###
